import type { OpenApiCatalog } from './OpenApiCatalog.ts';

export const seedCatalog: OpenApiCatalog = {
  title: 'Trakt API',
  apiVersion: '2',
  openApiVersion: '3.0',
  source: 'Bundled starter catalog',
  endpoints: [
    {
      id: 'moviesSummary',
      method: 'GET',
      path: '/movies/{id}',
      summary: 'Get a movie',
      description: 'Returns a single movie with optional extended information.',
      operationId: 'moviesSummary',
      tags: ['Movies'],
      deprecated: false,
      auth: 'optional',
      parameters: [
        {
          id: 'path:id',
          name: 'id',
          location: 'path',
          required: true,
          description: 'Trakt ID, Trakt slug, or IMDB ID.',
          type: 'string',
          enumValues: [],
          defaultValue: 'tron-legacy-2010',
        },
        {
          id: 'query:extended',
          name: 'extended',
          location: 'query',
          required: false,
          description: 'Add more information to the response.',
          type: 'string',
          enumValues: ['min', 'full'],
          defaultValue: 'full',
        },
      ],
      requestBody: null,
      responses: [{
        status: '200',
        description: 'Movie information',
        contentType: 'application/json',
        example: '',
        requiredExample: '',
      }],
      serverUrls: ['https://api.trakt.tv'],
    },
    {
      id: 'searchTextQuery',
      method: 'GET',
      path: '/search/{type}',
      summary: 'Search by text query',
      description: 'Searches titles, people, and lists by free-form text.',
      operationId: 'searchTextQuery',
      tags: ['Search'],
      deprecated: false,
      auth: 'optional',
      parameters: [
        {
          id: 'path:type',
          name: 'type',
          location: 'path',
          required: true,
          description: 'Type of item to search.',
          type: 'string',
          enumValues: ['movie', 'show', 'episode', 'person', 'list'],
          defaultValue: 'movie',
        },
        {
          id: 'query:query',
          name: 'query',
          location: 'query',
          required: true,
          description: 'Search terms.',
          type: 'string',
          enumValues: [],
          defaultValue: 'tron',
        },
      ],
      requestBody: null,
      responses: [{
        status: '200',
        description: 'Search results',
        contentType: 'application/json',
        example: '',
        requiredExample: '',
      }],
      serverUrls: ['https://api.trakt.tv'],
    },
    {
      id: 'syncHistoryAdd',
      method: 'POST',
      path: '/sync/history',
      summary: 'Add items to watched history',
      description: 'Adds movies and episodes to the selected account history.',
      operationId: 'syncHistoryAdd',
      tags: ['Sync'],
      deprecated: false,
      auth: 'required',
      parameters: [],
      requestBody: {
        required: true,
        description: 'Movies and episodes to add.',
        contentType: 'application/json',
        example:
          '{\n  "movies": [\n    {\n      "ids": {\n        "trakt": 343\n      }\n    }\n  ]\n}',
      },
      responses: [{
        status: '201',
        description: 'Items added',
        contentType: 'application/json',
        example: '',
        requiredExample: '',
      }],
      serverUrls: ['https://api.trakt.tv'],
    },
    {
      id: 'syncRatingsAdd',
      method: 'POST',
      path: '/sync/ratings',
      summary: 'Add ratings',
      description: 'Rates one or more movies, shows, seasons, or episodes.',
      operationId: 'syncRatingsAdd',
      tags: ['Sync'],
      deprecated: false,
      auth: 'required',
      parameters: [],
      requestBody: {
        required: true,
        description: 'Rated media items.',
        contentType: 'application/json',
        example:
          '{\n  "movies": [\n    {\n      "rating": 9,\n      "ids": {\n        "trakt": 343\n      }\n    }\n  ]\n}',
      },
      responses: [{
        status: '201',
        description: 'Ratings added',
        contentType: 'application/json',
        example: '',
        requiredExample: '',
      }],
      serverUrls: ['https://api.trakt.tv'],
    },
    {
      id: 'syncWatchlistRemove',
      method: 'DELETE',
      path: '/sync/watchlist/remove',
      summary: 'Remove items from watchlist',
      description:
        'Removes one or more items from the selected account watchlist.',
      operationId: 'syncWatchlistRemove',
      tags: ['Sync'],
      deprecated: false,
      auth: 'required',
      parameters: [],
      requestBody: {
        required: true,
        description: 'Media items to remove.',
        contentType: 'application/json',
        example:
          '{\n  "movies": [\n    {\n      "ids": {\n        "trakt": 343\n      }\n    }\n  ]\n}',
      },
      responses: [{
        status: '200',
        description: 'Items removed',
        contentType: 'application/json',
        example: '',
        requiredExample: '',
      }],
      serverUrls: ['https://api.trakt.tv'],
    },
  ],
};
