/**
 * Fully typed [ts-rest](https://ts-rest.com) contract and client for the
 * [Trakt API](https://trakt.docs.apiary.io), backed by Zod schemas.
 *
 * `traktApi()` returns a client with precise request/response types for every
 * endpoint; the individual Zod schemas and inferred model types are also
 * exported for validation and reuse.
 *
 * @example
 * ```ts
 * import { traktApi } from '@trakt/api';
 *
 * const client = traktApi({ apiKey: '<client-id>' });
 *
 * const res = await client.movies.summary({ params: { id: 'tron-legacy-2010' } });
 * if (res.status === 200) {
 *   console.log(res.body.title); // fully typed
 * }
 * ```
 *
 * @module
 */

// Runtime comes from `./src/index.ts`; the public types come from the
// precomputed static declarations in `./types` (generated by
// `deno task build:types`). Serving explicit declarations instead of the
// fully-inferred Zod + ts-rest types keeps the package free of JSR "slow
// types" and gives consumers fast, static type-checking.
//
// @ts-types="./types/index.d.ts"
export * from './src/index.ts';
