// Published entry point.
//
// Runtime comes from `./src/index.ts`; the public types come from the
// precomputed static declarations in `./types` (generated by
// `deno task build:types`). Serving explicit declarations instead of the
// fully-inferred Zod + ts-rest types keeps the package free of JSR "slow
// types" and gives consumers fast, static type-checking.
//
// @ts-types="./types/index.d.ts"
export * from './src/index.ts';
