import { z } from '../z.ts';

// TODO split up in separate schemas
export const jobResponseSchema = z.enum([
  'Producer',
  'Production Manager',
  'Co-Producer',
  'Associate Producer',
  'Visual Effects Producer',
  'Executive Producer',
  'Co-Executive Producer',
  'Line Producer',

  // Directing jobs
  'Action Director',
  'Additional Second Assistant Director',
  'Additional Third Assistant Director',
  'Assistant Director',
  'Co-Director',
  'Crowd Assistant Director',
  'Director',
  'Field Director',
  'First Assistant Director',
  'Insert Unit Director',
  'Insert Unit First Assistant Director',

  'Second Assistant Director',
  'Second Second Assistant Director',
  'Second Unit Director',
  'Second Unit First Assistant Director',
  'Series Director',
  'Special Guest Director',
  'Stage Director',
  'Third Assistant Director',

  // Writing jobs
  'Author',
  'Book',
  'Characters',
  'Co-Writer',
  'Comic Book',
  'Creative Producer',
  'Executive Story Editor',
  'Graphic Novel',
  'Head of Story',
  'Idea',
  'Lyricist',
  'Musical',
  'Novel',
  'Opera',
  'Original Concept',
  'Original Film Writer',
  'Original Series Creator',
  'Original Story',
  'Other',
  'Scenario Writer',
  'Screenplay',
  'Screenstory',
  'Script Consultant',
  'Script Editor',
  'Senior Story Editor',
  'Series Composition',
  'Short Story',
  'Staff Writer',
  'Story',
  'Story Artist',
  'Story Consultant',
  'Story Coordinator',
  'Story Developer',
  'Story Editor',
  'Story Manager',
  'Story Supervisor',
  'Storyboard',
  'Writer',
  "Writers' Assistant",
  "Writers' Production",
]);
