import { asString, z } from '../z.ts';

// TODO split up in separate schemas
export const jobResponseSchema = asString(z.enum([
  /*
    Temporary list to type mock responses.
    TODO @seferturan: update this list with all job titles.
  */
  'Casting Coordinator',
  'Producer',
  'Production Manager',
  'Co-Producer',
  'Associate Producer',
  'Local Casting',
  'Casting',
  'Casting Associate',
  'Costume Coordinator',
  'Key Makeup Artist',
  'Makeup Effects Designer',
  'Hair Department Head',
  'Special Effects Makeup Artist',
  'Key Hair Stylist',
  'Makeup Department Head',
  'Costume Design',
  'Costume Supervisor',
  'Prosthetic Designer',
  'Transportation Captain',
  'Thanks',
  'Post Production Supervisor',
  'Cast Driver',
  'Stunt Double',
  'Visual Effects Supervisor',
  'Visual Effects Producer',
  'Sound Effects Editor',
  'Production Sound Mixer',
  'Music Editor',
  'Foley Recordist',
  'Foley Editor',
  'Sound Designer',
  'Music Supervisor',
  'Music',
  'Sound Re-Recording Mixer',
  'Editor',
  'Production Design',
  'Graphic Designer',
  'Set Dresser',
  'Assistant Art Director',
  'Set Decoration',
  'Art Direction',
  'Property Master',
  'Construction Coordinator',
  'Title Designer',
  'Steadicam Operator',
  'Director of Photography',
  'Lighting Technician',
  'Executive Producer',
  'Co-Executive Producer',
  'Line Producer',
  'Supervising Sound Editor',
  'Dialogue Editor',
  'Foley Mixer',
  'Foley Artist',
  'Original Music Composer',
  'Supervising Art Director',
  'Special Effects Supervisor',
  'Hair Designer',
  'Makeup Designer',
  'Colorist',
  'Creator',
  'Stunts',

  //Production jobs
  'Unit Production Manager',
  'Location Manager',
  'Production Supervisor',
  'Production Accountant',
  'Executive In Charge Of Production',
  'Coordinating Producer',
  'Assistant Accountant',
  'Supervising Producer',
  'Post Production Coordinator',
  'Additional Production Assistant',
  'Assistant Location Manager',
  'Assistant Production Coordinator',
  "Executive Producer's Assistant",
  'First Assistant Accountant',
  'Production Assistant',
  'Production Coordinator',
  'Second Assistant Accountant',
  'Production Office Assistant',
  'Production Controller',
  'Set Production Assistant',
  'Post Production Assistant',

  //Editing jobs
  'First Assistant Editor',
  'Assistant Editor',
  'Color Timer',
  'Associate Editor',
  'Negative Cutter',
  'Color Assistant',
  'Digital Color Timer',

  //Art Department jobs
  'Set Designer',
  'Construction Foreman',
  'Concept Artist',
  'Art Department Coordinator',
  'Greensman',
  'Leadman',
  'Lead Painter',
  'Assistant Property Master',
  'Props',
  'Painter',
  'Standby Painter',
  'Carpenter',
  'Prop Maker',
  'Sculptor',
  'On Set Dresser',
  'Modeling',

  //Sound jobs
  'Conductor',
  'Orchestrator',
  'Foley',
  'Boom Operator',
  'Musician',
  'Additional Sound Re-Recording Mixer',
  'First Assistant Sound Editor',
  'Sound Mixer',
  'Scoring Mixer',
  'ADR Mixer',
  'Music Consultant',
  'Music Score Producer',
  'Additional Music',
  'Score Engineer',

  //Special Effects jobs
  'Special Effects Technician',
  'Special Effects',
  'Special Effects Coordinator',
  'Special Effects Assistant',

  //Stunts jobs
  'Stunt Coordinator',

  //Transportation jobs
  'Transportation Coordinator',
  'Driver',

  //Visual Effects jobs
  'Executive Visual Effects Producer',
  'Visual Effects Editor',
  'CG Supervisor',
  'Sequence Supervisor',
  'Compositor',
  'Digital Effects Supervisor',
  'Visual Effects Coordinator',
  'Digital Compositor',
  'Animation',
  'VFX Artist',
  'Rotoscoping Artist',
  'Visual Effects Production Assistant',
  'Visual Effects Assistant Editor',
  'VFX Director of Photography',
  'Matchmove Supervisor',
  'Pre-Visualization Supervisor',
  'Visual Effects Technical Director',
  'Visual Effects Production Manager',
  'Compositing Lead',
  'Matte Painter',
  'Animation Supervisor',
  'Compositing Supervisor',
  'Senior Modeller',
  'Visual Effects',
  'Visual Effects Camera',

  //Camera jobs
  'Camera Operator',
  'Helicopter Camera',
  'Camera Technician',
  'First Assistant Camera',
  'First Assistant "A" Camera',
  'First Assistant "B" Camera',
  'Epk Camera Operator',
  'Second Assistant "B" Camera',
  'Assistant Camera',
  'Second Assistant "A" Camera',
  'Camera Production Assistant',
  'Camera Loader',
  'Data Wrangler',
  'Video Assist Operator',
  'Still Photographer',

  //Lighting/Grip jobs
  'Rigging Grip',
  'Rigging Gaffer',
  'Gaffer',
  'Electrician',
  'Key Rigging Grip',
  'Grip',
  'Key Grip',
  'Dolly Grip',
  'Best Boy Grip',

  //Directing jobs
  'Action Director',
  'Assistant Director',
  'Co-Director',
  'Continuity',
  'Crowd Assistant Director',
  'Director',
  'Field Director',
  'First Assistant Director',
  'Insert Unit Director',
  'Insert Unit First Assistant Director',
  'Layout',
  'Other',
  'Script Coordinator',
  'Script Supervisor',
  'Series Director',
  'Special Guest Director',
  'Stage Director',
  'Second Assistant Director',
  'Second Second Assistant Director',
  'Third Assistant Director',
  'Additional Second Assistant Director',

  //Writing jobs
  'Adaptation',
  'Author',
  'Book',
  'Characters',
  'Co-Writer',
  'Comic Book',
  'Creative Producer',
  'Dialogue',
  'Executive Story Editor',
  'Graphic Novel',
  'Head of Story',
  'Idea',
  'Lyricist',
  'Musical',
  'Novel',
  'Opera',
  'Original Concept',
  'Original Film Writer',
  'Original Series Creator',
  'Original Story',
  'Scenario Writer',
  'Screenplay',
  'Screenstory',
  'Script Consultant',
  'Script Editor',
  'Senior Story Editor',
  'Series Composition',
  'Short Story',
  'Staff Writer',
  'Story',
  'Story Artist',
  'Story Consultant',
  'Story Coordinator',
  'Story Developer',
  'Story Editor',
  'Story Manager',
  'Story Supervisor',
  'Storyboard',
  'Teleplay',
  'Texte',
  'Theatre Play',
  'Writer',
  "Writers' Assistant",
  "Writers' Production",

  //Other jobs
  'Pilot',
  'Dialect Coach',
  'Set Medic',
  'Technical Advisor',
  'Loader',
  'Catering',
  'Craft Service',
  'Security Coordinator',
  'Set Costumer',
  'Makeup Artist',
  'Hairstylist',
  'Costumer',
  'Key Costumer',
  'Prosthetics',
]));
