import { z } from '../z.ts';

export const upNextSortBySchema = z.enum([
  'activity',
  'added',
  'completed',
  'episodes',
  'time',
  'plays',
  'released',
  'premiered',
  'title',
  'popularity',
  'runtime',
  'total-runtime',
  'recently-aired',
  'random',
  'most-completed',
  'least-completed',
  'most-time',
  'least-time',
  'most-plays',
  'least-plays',
  'most-episodes',
  'least-episodes',
  'oldest-activity',
  'previously-aired',
]);